# Generated by Django 3.0.7 on 2020-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
