# Generated by Django 3.0.7 on 2020-06-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200630_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
    ]
